# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QSlider

import RobotState_and_image_State


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(492, 534)
        Form.setMinimumSize(QtCore.QSize(492, 534))
        Form.setMaximumSize(QtCore.QSize(492, 534))
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(280, 30, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 30, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(270, 60, 141, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBoxMotionTime = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxMotionTime.setEnabled(True)
        self.checkBoxMotionTime.setObjectName("checkBoxMotionTime")
        self.verticalLayout_2.addWidget(self.checkBoxMotionTime)
        self.checkBoxSpeed = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxSpeed.setObjectName("checkBoxSpeed")
        self.verticalLayout_2.addWidget(self.checkBoxSpeed)
        self.checkBoxDistance = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxDistance.setObjectName("checkBoxDistance")
        self.verticalLayout_2.addWidget(self.checkBoxDistance)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(120, 260, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(250, 260, 91, 16))
        self.label_5.setObjectName("label_5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 290, 391, 171))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalSliderRobotSpeed = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.verticalSliderRobotSpeed.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.verticalSliderRobotSpeed.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderRobotSpeed.setObjectName("verticalSliderRobotSpeed")
        self.horizontalLayout.addWidget(self.verticalSliderRobotSpeed)
        self.verticalSliderServoSpeed = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.verticalSliderServoSpeed.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.verticalSliderServoSpeed.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderServoSpeed.setObjectName("verticalSliderServoSpeed")
        self.horizontalLayout.addWidget(self.verticalSliderServoSpeed)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 70, 101, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.checkBoxCellPhone = QtWidgets.QCheckBox(Form)
        self.checkBoxCellPhone.setGeometry(QtCore.QRect(130, 120, 91, 20))
        self.checkBoxCellPhone.setObjectName("checkBoxCellPhone")
        self.checkBoxPerson = QtWidgets.QCheckBox(Form)
        self.checkBoxPerson.setGeometry(QtCore.QRect(130, 77, 81, 20))
        self.checkBoxPerson.setObjectName("checkBoxPerson")
        self.checkBoxBottle = QtWidgets.QCheckBox(Form)
        self.checkBoxBottle.setGeometry(QtCore.QRect(130, 163, 81, 20))
        self.checkBoxBottle.setObjectName("checkBoxBottle")

        self.retranslateUi(Form)
        self.checkBoxPerson.stateChanged.connect(self.choseObject)
        self.checkBoxCellPhone.stateChanged.connect(self.choseObject)
        self.checkBoxBottle.stateChanged.connect(self.choseObject)
        self.checkBoxMotionTime.stateChanged.connect(self.choseObject)
        self.checkBoxSpeed.stateChanged.connect(self.choseObject)
        self.checkBoxDistance.stateChanged.connect(self.choseObject)
        self.verticalSliderRobotSpeed.setMinimum(1)
        self.verticalSliderRobotSpeed.setMaximum(10)
        self.verticalSliderRobotSpeed.setSingleStep(1)
        self.verticalSliderRobotSpeed.setTickPosition(QSlider.TicksRight)
        self.verticalSliderRobotSpeed.valueChanged.connect(self.sliderValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def sliderValue(self):
        RobotState_and_image_State.robotspeed = self.verticalSliderRobotSpeed.value() / 10
        print("Robot speed has changed {0}".format(self.verticalSliderRobotSpeed.value()))

    def choseObject(self):
        if self.checkBoxPerson.isChecked() == True:
            RobotState_and_image_State.objectischecked["person"] = True
        else:
            RobotState_and_image_State.objectischecked["person"] = False
        if self.checkBoxCellPhone.isChecked() == True:
            RobotState_and_image_State.objectischecked["cell phone"] = True
        else:
            RobotState_and_image_State.objectischecked["cell phone"] = False
        if self.checkBoxBottle.isChecked() == True:
            RobotState_and_image_State.objectischecked["bottle"] = True
        else:
            RobotState_and_image_State.objectischecked["bottle"] = False
        if self.checkBoxSpeed.isChecked() == True:
            RobotState_and_image_State.parameterischecked["speed"] = True
        else:
            RobotState_and_image_State.parameterischecked["speed"] = False
        if self.checkBoxDistance.isChecked() == True:
            RobotState_and_image_State.parameterischecked["distance"] = True
        else:
            RobotState_and_image_State.parameterischecked["distance"] = False
        if self.checkBoxMotionTime.isChecked() == True:
            RobotState_and_image_State.parameterischecked["motion"] = True
        else:
            RobotState_and_image_State.parameterischecked["motion"] = False
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Select Data to receive"))
        self.label_2.setText(_translate("Form", "Select Object to recognize"))
        self.checkBoxMotionTime.setText(_translate("Form", "Object Motion Time"))
        self.checkBoxSpeed.setText(_translate("Form", "Object Speed"))
        self.checkBoxDistance.setText(_translate("Form", "Object Distance"))
        self.label_4.setText(_translate("Form", "Robot speed"))
        self.label_5.setText(_translate("Form", "Servo speed"))
        self.checkBoxCellPhone.setText(_translate("Form", "Cell Phone"))
        self.checkBoxPerson.setText(_translate("Form", "Person"))
        self.checkBoxBottle.setText(_translate("Form", "Bottle"))
